# required-arch-package :: i3status-rust
# required-arch-package :: networkmanager
# required-arch-package :: pavucontrol
# required-arch-package :: ttf-font-awesome
[theme]
theme = "space-villain"
[icons]
icons = "awesome6"

[[block]]
block = "music"
player = "spotify"
format = " $icon {$title - $artist $play $next|}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = " $icon 1min avg: $1m.eng(w:4) "

[[block]]
block = "net"
format = " $icon {$ssid |} ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
[[block.click]]
button = "left"
cmd = "terminator -e nmtui"

[[block]]
block = "backlight"
minimum = 10
maximum = 100
step_width = 5
invert_icons = true
if_command = "test -e /sys/class/backlight/*"

[[block]]
block = "battery"
format = "$icon {$percentage} {$time}"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "custom"
json = true
interval = "once"
signal = 4
command = ". /home/matt/.config/sway/scripts/idle-check.sh"
[[block.click]]
button = "left"
cmd = ". /home/matt/bin/idle-toggle"

[[block]]
block = "sound"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "
