# required-arch-package :: i3status-rust
# required-arch-package :: networkmanager
# required-arch-package :: pavucontrol
# required-arch-package :: socranop
# required-arch-package :: ttf-font-awesome
[theme]
theme = "space-villain"
[icons]
icons = "awesome6"

[[block]]
block = "music"
format = " $icon {$combo $play $next|} "
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
[[block.click]]
button = "forward"
action = "seek_forward"
[[block.click]]
button = "back"
action = "seek_backward"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = " $icon 1min avg: $1m.eng(w:4) "

[[block]]
block = "net"
format = " $icon {$ssid |} ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
[[block.click]]
button = "left"
cmd = "terminator -e nmtui"

[[block]]
block = "backlight"
minimum = 10
maximum = 100
step_width = 5
invert_icons = true
if_command = "test -e /sys/class/backlight/*"

[[block]]
block = "battery"
format = " $icon {$percentage} {$time} "
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "sound"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
json = true
interval = "once"
signal = 5
command = ". /home/matt/.config/sway/scripts/socranop-check.sh"
if_command = "lsusb -d 05fc:0031 >/dev/null"
[block.icons_overrides]
icon = "\uf1de"
[[block.click]]
button = "left"
cmd = "pkill -SIGRTMIN+5 i3status-rs"
[[block.click]]
button = "right"
cmd = ". /home/matt/.config/sway/scripts/socranop-cycle.sh"

[[block]]
block = "custom"
json = true
interval = "once"
signal = 4
command = ". /home/matt/.config/sway/scripts/idle-check.sh"
[[block.click]]
button = "left"
cmd = ". /home/matt/bin/idle-toggle"
[block.icons_overrides]
lock = "\uf023"
lock-open = "\uf3c1"

[[block]]
block = "toggle"
format = " $icon "
command_on = "makoctl mode -a do-not-disturb >/dev/null"
command_off = "makoctl mode -r do-not-disturb >/dev/null"
command_state = "makoctl mode | grep do-not-disturb"
icon_on = "bell-slash"
icon_off = "bell"
state_on = "warning"
[block.icons_overrides]
bell-slash = "\uf1f6"
bell = "\uf0f3"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "
